# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\m1582\Documents\GitHub\first\auto-first\home.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 151)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_filename = QtWidgets.QLabel(self.centralwidget)
        self.label_filename.setObjectName("label_filename")
        self.gridLayout.addWidget(self.label_filename, 2, 1, 1, 1)
        self.label_program = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_program.sizePolicy().hasHeightForWidth())
        self.label_program.setSizePolicy(sizePolicy)
        self.label_program.setMinimumSize(QtCore.QSize(150, 50))
        self.label_program.setMaximumSize(QtCore.QSize(100, 50))
        self.label_program.setBaseSize(QtCore.QSize(0, 30))
        self.label_program.setObjectName("label_program")
        self.gridLayout.addWidget(self.label_program, 0, 0, 1, 1)
        self.label_time = QtWidgets.QLabel(self.centralwidget)
        self.label_time.setObjectName("label_time")
        self.gridLayout.addWidget(self.label_time, 2, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_filename.setText(_translate("MainWindow", "filename"))
        self.label_program.setText(_translate("MainWindow", "program"))
        self.label_time.setText(_translate("MainWindow", "time"))
